package ru.sevsu.kirillrudnikov.crud.entity;

public enum CarBrand {

    ABARTH, AC, ACURA, ALFA_ROMEO, ALPINA, ASTON_MARTIN, AUDI,
    BAIC, BAVARIA, BAW, BENTLEY, BMW, BOGDAN, BRILLIANCE, BUGATTI, BUICK, BYD, BELAZ,
    CADILLAC, CATERHAM, CHANGAN, CHARRON, CHERY, CHEVROLET, CHEVROLET_CORVETTE, CHRYSLER, CITROEN,
    DACIA, DAEWOO, DAF, DAIHATSU, DAIMLER, DODGE, DUCATI,
    EDCEL, EAGLE,
    FAW, FERRARI, FIAT, FISKER, FORD, FSO,
    GEELY, GMC, GOLIATH, GREAT_WALL, GAZ,
    HAFEI, HAIMA, HIGER, HONDA, HUMMER, HYUNDAI,
    INFINITI, ISUZU, IVECO,
    JAC, JAGUAR, JEEP,
    KIA, KOENIGSEGG, KRAZ, KAMAZ,
    LADA, LAMBORGHINI, LANCIA, LAND_ROVER, LANDWIND, LEXUS, LIFAN, LINCOLN,
    MARUSSIA, MASERATTI, MAYBACH, MAZDA, MCLAREN, MERCEDES_BENZ, MERCURY, MG_CAR_COMPANY, MINI, MITSUBISHI, MOSKVISH,
    NISSAN, NOBLE, OLDSMOBILE, OPEL,
    PACKARD, PAGANI, PANOZ, PEUGEOT, PLYMOUTH, PONTIAC, PORSCHE, PROTON,
    RENAULT, ROLLS_ROYCE, ROVER,
    SAAB, SATURN, SCANIA, SCION, SEAT, SKODA, SMART, SSANG_YONG, SUBARU, SUZUKI,
    TALBOT, TATRA, TESLA, TOYOTA, TRABANT, TVR, TAGAZ,
    URALAZ, UAZ,
    VERITAS, VOLKSWAGEN, VOLVO, VORTEX,
    ZAZ, ZIL

}

//package ru.sevsu.kirillrudnikov.springproject.entity;
//
//public enum CarBrand {
//
//    ABARTH, AC, ACURA, ALFA_ROMEO, ALPINA, ASTON_MARTIN, AUDI,
//    BAIC, BAVARIA, BAW, BENTLEY, BMW, BOGDAN, BRILLIANCE, BUGATTI, BUICK, BYD,
//    CADILLAC, CATERHAM, CHANGAN, CHARRON, CHERY, CHEVROLET, CHEVROLET_CORVETTE, CHRYSLER, CITROEN,
//    DACIA, DAEWOO, DAF, DAIHATSU, DAIMLER, DODGE, DUCATI,
//    EDCEL, EAGLE,
//    FAW, FERRARI, FIAT, FISKER, FORD, FSO,
//    GEELY, GMC, GOLIATH, GREAT_WALL,
//    HAFEI, HAIMA, HIGER, HONDA, HUMMER, HYUNDAI,
//    INFINITI, ISUZU, IVECO,
//    JAC, JAGUAR, JEEP,
//    KIA, KOENIGSEGG, KRAZ,
//    LADA, LAMBORGHINI, LANCIA, LAND_ROVER, LANDWIND, LEXUS, LIFAN, LINCOLN,
//    MARUSSIA, MASERATTI, MAYBACH, MAZDA, MCLAREN, MERCEDES_BENZ, MERCURY, MG_CAR_COMPANY, MINI, MITSUBISHI,
//    NISSAN, NOBLE, OLDSMOBILE, OPEL,
//    PACKARD, PAGANI, PANOZ, PEUGEOT, PLYMOUTH, PONTIAC, PORSCHE, PROTON,
//    RENAULT, ROLLS_ROYCE, ROVER,
//    SAAB, SATURN, SCANIA, SCION, SEAT, SKODA, SMART, SSANG_YONG, SUBARU, SUZUKI,
//    TALBOT, TATRA, TESLA, TOYOTA, TRABANT, TVR,
//    VERITAS, VOLKSWAGEN(""), VOLVO("Volvo"), VORTEX("Vortex"), ZAZ("ЗАЗ"), BELAZ("БелАЗ");
//
//    private final String name;
//
//    CarBrand(String name) {
//        this.name = name;
//    }
//}